# Generated by Django 6.0.4 on 2026-04-28 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category_order', models.PositiveIntegerField(default=0)),
                ('item_text', models.TextField()),
                ('item_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'safety_check_items',
                'ordering': ['category_order', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('critical', '중대')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', '발생'), ('investigating', '조사 중'), ('closed', '종료')], default='open', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='facilities.facility')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='facilities.worker')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='facilities.zone')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_title', models.CharField(max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', '미완료'), ('in_progress', '진행 중'), ('completed', '완료')], default='open', max_length=20)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='safety.incident')),
            ],
            options={
                'db_table': 'corrective_actions',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('hazard_type', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')], max_length=20)),
                ('action_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', '작성 중'), ('active', '적용 중'), ('archived', '보관')], default='draft', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='facilities.facility')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to='facilities.zone')),
            ],
            options={
                'db_table': 'risk_assessments',
            },
        ),
        migrations.CreateModel(
            name='SafetyCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('checklist_completed', models.BooleanField(default=False)),
                ('checklist_completed_at', models.DateTimeField(blank=True, null=True)),
                ('vr_completed', models.BooleanField(default=False)),
                ('vr_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_sessions', to='facilities.facility')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_sessions', to='facilities.worker')),
            ],
            options={
                'db_table': 'safety_check_sessions',
                'ordering': ['-check_date'],
                'unique_together': {('worker', 'check_date')},
            },
        ),
        migrations.CreateModel(
            name='WorkPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_type', models.CharField(max_length=50)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인'), ('rejected', '반려'), ('expired', '만료')], default='pending', max_length=20)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_permits', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_permits', to='facilities.facility')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_permits', to='facilities.worker')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_permits', to='facilities.zone')),
            ],
            options={
                'db_table': 'work_permits',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyCheckItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='safety.safetycheckitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='safety.safetychecksession')),
            ],
            options={
                'db_table': 'safety_check_item_results',
                'unique_together': {('session', 'item')},
            },
        ),
    ]
