# Generated by Django 6.0.4 on 2026-05-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetycheckitem',
            name='answer_type',
            field=models.CharField(choices=[('체크 박스', '체크 박스'), ('주관식', '주관식')], default='체크 박스', max_length=20),
        ),
        migrations.AddField(
            model_name='safetycheckitem',
            name='category_description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
