# Generated by Django 6.0.3 on 2026-04-22 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('safety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('category_order', models.PositiveIntegerField(default=0)),
                ('item_text', models.TextField()),
                ('item_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'safety_check_items',
                'ordering': ['category_order', 'item_order'],
            },
        ),
        migrations.CreateModel(
            name='SafetyCheckSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('checklist_completed', models.BooleanField(default=False)),
                ('checklist_completed_at', models.DateTimeField(blank=True, null=True)),
                ('vr_completed', models.BooleanField(default=False)),
                ('vr_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_sessions', to='facilities.facility')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_sessions', to='facilities.worker')),
            ],
            options={
                'db_table': 'safety_check_sessions',
                'ordering': ['-check_date'],
                'unique_together': {('worker', 'check_date')},
            },
        ),
        migrations.CreateModel(
            name='SafetyCheckItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='safety.safetycheckitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_results', to='safety.safetychecksession')),
            ],
            options={
                'db_table': 'safety_check_item_results',
                'unique_together': {('session', 'item')},
            },
        ),
    ]
