# Generated by Django 6.0.4 on 2026-05-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    # 모든 필드는 0002_commoncode_scope..., 0003_commoncode_description, 0004_add_map_reflect에서 이미 추가됨
    operations = []
