# Generated by Django 6.0.4 on 2026-05-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='actor_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='target_id',
            field=models.BigIntegerField(),
        ),
    ]
