# Generated by Django 6.0.4 on 2026-05-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncode',
            name='scope',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='commoncode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commoncode',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
