# Generated by Django 6.0.4 on 2026-05-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_changelog_actor_id_alter_changelog_target_id'),
        ('core', '0002_commoncode_description_commoncode_map_reflect_and_more'),
    ]

    operations = [
    ]
