# Generated by Django 6.0.4 on 2026-05-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commoncode_scope_commoncode_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncode',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
