# Generated by Django 6.0.4 on 2026-05-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_commoncode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='commoncode',
            name='map_reflect',
            field=models.BooleanField(default=False),
        ),
    ]
