# Generated by Django 6.0.4 on 2026-05-13 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commoncode_description_commoncode_map_reflect_and_more'),
        ('core', '0004_add_map_reflect'),
    ]

    operations = [
    ]
