# Generated by Django 6.0.4 on 2026-05-14 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260514_1008'),
        ('core', '0005_merge_20260513_1314'),
    ]

    operations = [
    ]
