# Generated by Django 6.0.3 on 2026-04-23 14:30

import django.db.models.deletion
import facilities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_code', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '운영중'), ('inactive', '비운영'), ('maintenance', '점검중')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '사업장',
                'verbose_name_plural': '사업장 목록',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_no', models.CharField(max_length=50, unique=True)),
                ('worker_name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('on_duty', '근무중'), ('off_duty', '비근무'), ('danger', '위험')], default='on_duty', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '작업자',
                'verbose_name_plural': '작업자 목록',
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=200)),
                ('building_code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='facilities.facility')),
            ],
            options={
                'verbose_name': '건물',
                'verbose_name_plural': '건물 목록',
                'db_table': 'buildings',
                'unique_together': {('facility', 'building_code')},
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100)),
                ('floor_no', models.IntegerField()),
                ('plan_image', models.ImageField(blank=True, help_text='해당 층의 도면 이미지', null=True, upload_to=facilities.models.floor_plan_path)),
                ('width', models.IntegerField(help_text='건물 가로 길이(m)')),
                ('length', models.IntegerField(help_text='건물 세로 길이(m)')),
                ('height', models.IntegerField(blank=True, help_text='층고(m) - 추후 사용', null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='facilities.building')),
            ],
            options={
                'verbose_name': '층',
                'verbose_name_plural': '층 목록',
                'db_table': 'floors',
                'ordering': ['floor_no'],
                'unique_together': {('building', 'floor_no')},
            },
        ),
        migrations.CreateModel(
            name='FloorGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_size', models.FloatField(default=1.0, help_text='격자 한 칸의 실제 크기 (m)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grid', to='facilities.floor')),
            ],
            options={
                'verbose_name': '층 격자 설정',
                'verbose_name_plural': '층 격자 설정 목록',
                'db_table': 'floor_grids',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=100)),
                ('zone_type', models.CharField(choices=[('work', '작업구역'), ('storage', '창고'), ('rest', '휴게구역'), ('utility', '설비구역'), ('passage', '통로'), ('etc', '기타')], default='work', max_length=20)),
                ('cell_row_start', models.PositiveIntegerField(default=0)),
                ('cell_row_end', models.PositiveIntegerField(default=0)),
                ('cell_col_start', models.PositiveIntegerField(default=0)),
                ('cell_col_end', models.PositiveIntegerField(default=0)),
                ('color', models.CharField(default='#378ADD', help_text='지도 표시 색상 hex', max_length=20)),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='facilities.floor')),
            ],
            options={
                'verbose_name': '구역',
                'verbose_name_plural': '구역 목록',
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_no', models.CharField(blank=True, help_text="'row-col' 형식 예: '3-5'", max_length=20)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.building')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.facility')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.floor')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='facilities.worker')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.zone')),
            ],
            options={
                'verbose_name': '작업자 위치',
                'db_table': 'worker_locations',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=100)),
                ('node_code', models.CharField(max_length=50)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('z', models.FloatField(default=0, null=True)),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_nodes', to='facilities.zone')),
            ],
            options={
                'verbose_name': '위치 노드',
                'db_table': 'location_nodes',
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('center_x', models.FloatField(help_text='원 중심 x (px)')),
                ('center_y', models.FloatField(help_text='원 중심 y (px)')),
                ('radius', models.FloatField(help_text='반지름 (px)')),
                ('severity', models.CharField(choices=[('danger', '위험'), ('warning', '주의'), ('safe', '안전')], default='danger', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='facilities.floor')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofences', to='facilities.zone')),
            ],
            options={
                'verbose_name': '위험구역',
                'verbose_name_plural': '위험구역 목록',
                'db_table': 'geofences',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=20)),
                ('equipment_code', models.CharField(max_length=20)),
                ('floor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='facilities.floor')),
                ('zone', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.zone')),
            ],
            options={
                'verbose_name': '설비',
                'verbose_name_plural': '설비 목록',
                'db_table': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='IndexGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_index', models.IntegerField(help_text='격자 고유 번호 (Row-Major, 왼쪽 위부터 가로 순번)')),
                ('col', models.IntegerField(help_text='열 번호 (x 방향, 0부터 시작)')),
                ('row', models.IntegerField(help_text='행 번호 (y 방향, 0부터 시작)')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_grids', to='facilities.floor')),
            ],
            options={
                'verbose_name': '격자 인덱스',
                'verbose_name_plural': '격자 인덱스 목록',
                'db_table': 'index_grids',
                'indexes': [models.Index(fields=['floor', 'grid_index'], name='index_grids_floor_i_8c32ed_idx'), models.Index(fields=['floor', 'col', 'row'], name='index_grids_floor_i_fdb339_idx')],
                'unique_together': {('floor', 'grid_index')},
            },
        ),
    ]
