# Generated by Django 6.0.4 on 2026-04-22 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_code', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('active', '운영 중'), ('inactive', '운영 중지')], default='active', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=200)),
                ('building_code', models.CharField(max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='facilities.facility')),
            ],
            options={
                'db_table': 'buildings',
                'unique_together': {('facility', 'building_code')},
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=100)),
                ('floor_no', models.IntegerField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='facilities.building')),
            ],
            options={
                'db_table': 'floors',
                'ordering': ['floor_no'],
                'unique_together': {('building', 'floor_no')},
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_no', models.CharField(max_length=50, unique=True)),
                ('worker_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', '재직 중'), ('inactive', '퇴직')], default='active', max_length=20)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(max_length=200)),
                ('zone_type', models.CharField(max_length=50)),
                ('polygon_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '운영 중'), ('inactive', '비활성')], default='active', max_length=20)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='facilities.floor')),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='WorkerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('z', models.FloatField(blank=True, null=True)),
                ('measured_at', models.DateTimeField()),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_locations', to='facilities.building')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_locations', to='facilities.facility')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_locations', to='facilities.floor')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='facilities.worker')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_locations', to='facilities.zone')),
            ],
            options={
                'db_table': 'worker_locations',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=200)),
                ('node_code', models.CharField(max_length=50, unique=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성')], default='active', max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_nodes', to='facilities.zone')),
            ],
            options={
                'db_table': 'location_nodes',
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geofence_type', models.CharField(choices=[('circle', '원형'), ('polygon', '다각형')], max_length=20)),
                ('radius_or_polygon', models.JSONField()),
                ('severity', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('critical', '위험')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='facilities.zone')),
            ],
            options={
                'db_table': 'geofences',
            },
        ),
    ]
