# Generated by Django 6.0.3 on 2026-04-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
