# Generated by Django 6.0.4 on 2026-04-29 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(help_text='monitoring.Device PK — FK 대신 정수로 참조 (앱 간 의존성 분리)', unique=True)),
                ('sensor_type', models.CharField(choices=[('gas', '가스센서'), ('power', '전력센서'), ('location', '위치노드')], default='gas', max_length=20)),
                ('x', models.FloatField(help_text='센서 x 좌표 (m)')),
                ('y', models.FloatField(help_text='센서 y 좌표 (m)')),
                ('device_name', models.CharField(blank=True, help_text='표시용 이름 (monitoring.Device.device_name 복사)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_locations', to='facilities.floor')),
            ],
            options={
                'verbose_name': '센서 위치',
                'verbose_name_plural': '센서 위치 목록',
                'db_table': 'sensor_locations',
            },
        ),
    ]
