# Generated by Django 6.0.4 on 2026-05-13 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationnode',
            name='is_placed',
            field=models.BooleanField(default=False, help_text='지도 배치 완료 여부'),
        ),
        migrations.AlterField(
            model_name='locationnode',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_nodes', to='facilities.floor'),
        ),
        migrations.AlterField(
            model_name='locationnode',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationnode',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
