# Generated by Django 6.0.3 on 2026-04-27 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='center_x',
            field=models.FloatField(blank=True, help_text='장비 중심점 x 좌표(m)', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='center_y',
            field=models.FloatField(blank=True, help_text='장비 중심점 y 좌표(m)', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='생성 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='height',
            field=models.FloatField(blank=True, help_text='장비 세로 크기(m)', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_placed',
            field=models.BooleanField(default=False, help_text='지도 배치 완료 여부'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rotation',
            field=models.IntegerField(default=0, help_text='회전 각도 (0/45/90/.../315)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', '운영중'), ('inactive', '비운영'), ('maintenance', '점검중')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='업데이트 내역'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='width',
            field=models.FloatField(blank=True, help_text='장비 가로 크기(m)', null=True),
        ),
        migrations.AlterField(
            model_name='workerlocation',
            name='z',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
