# Generated by Django 6.0.4 on 2026-04-29 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_sensorlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationnode',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_nodes', to='facilities.floor'),
        ),
        migrations.AlterField(
            model_name='locationnode',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_nodes', to='facilities.zone'),
        ),
    ]
