# Generated by Django 6.0.3 on 2026-04-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_equipment_center_x_equipment_center_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
