# Generated by Django 6.0.4 on 2026-05-13 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_locationnode_is_placed_alter_locationnode_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlocation',
            name='is_placed',
            field=models.BooleanField(default=False, help_text='지도 배치 완료 여부'),
        ),
        migrations.AlterField(
            model_name='sensorlocation',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_locations', to='facilities.floor'),
        ),
        migrations.AlterField(
            model_name='sensorlocation',
            name='x',
            field=models.FloatField(blank=True, help_text='센서 x 좌표 (m)', null=True),
        ),
        migrations.AlterField(
            model_name='sensorlocation',
            name='y',
            field=models.FloatField(blank=True, help_text='센서 y 좌표 (m)', null=True),
        ),
    ]
