# Generated by Django 6.0.4 on 2026-04-30 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_locationnode_floor_alter_locationnode_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='safety_status',
            field=models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', help_text='Geofence 판단 결과', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='current_state',
            field=models.CharField(choices=[('on_duty', '근무중'), ('off_duty', '비근무'), ('warning', '주의'), ('danger', '위험')], default='on_duty', max_length=20),
        ),
    ]
