# Generated by Django 6.0.4 on 2026-05-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_sensorlocation_is_placed_alter_sensorlocation_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='locationnode',
            name='node_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
