# Generated by Django 6.0.4 on 2026-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_worker_safety_status_alter_worker_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='current_state',
            field=models.CharField(choices=[('on_duty', '근무중'), ('off_duty', '비근무')], default='on_duty', max_length=20),
        ),
    ]
