# Generated by Django 6.0.4 on 2026-05-01 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_alter_worker_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerlocation',
            name='geofence',
            field=models.ForeignKey(blank=True, help_text='진입한 geofence (없으면 null)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='facilities.geofence'),
        ),
        migrations.AddField(
            model_name='workerlocation',
            name='safety_status',
            field=models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', help_text='해당 위치에서의 geofence 판단 결과', max_length=20),
        ),
    ]
