# Generated by Django 6.0.4 on 2026-05-03 05:16
import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0006_workerlocation_geofence_workerlocation_safety_status'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='workerlocation',
            name='geofence',
        ),
        migrations.RemoveField(
            model_name='workerlocation',
            name='safety_status',
        ),
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='accounts.department'),
        ),
    ]