# Generated by Django 6.0.4 on 2026-05-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_remove_workerlocation_geofence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerlocation',
            name='safety_status',
            field=models.CharField(choices=[('safe', '안전'), ('warning', '주의'), ('danger', '위험')], default='safe', max_length=20),
        ),
    ]
