# Generated by Django 6.0.4 on 2026-05-08 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_workerlocation_safety_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='power_system',
            field=models.CharField(blank=True, help_text='연결 전력 시스템 코드', max_length=50),
        ),
        migrations.AddField(
            model_name='equipment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_equipments', to=settings.AUTH_USER_MODEL),
        ),
    ]
