# Generated by Django 6.0.4 on 2026-05-14 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_equipment_equipment_code_and_more'),
        ('facilities', '0009_add_equipment_admin_fields'),
    ]

    operations = [
    ]
