# Generated by Django 6.0.4 on 2026-05-28 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0010_merge_20260514_1008'),
        ('monitoring', '0010_alter_thresholdpolicy_action_type_alert_to_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationnode',
            name='device',
            field=models.OneToOneField(blank=True, help_text='운영 메타데이터(담당자/점검/last_seen)와의 1:1 연결', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_node', to='monitoring.device'),
        ),
    ]
