apiVersion: v1
kind: ConfigMap
metadata:
  name: icmp2-config
  namespace: icmp2
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "monitoring_db"
  REDIS_URL: "redis://redis:6379/0"
  REDIS_HOST: "redis"
  FASTAPI_BASE_URL: "http://fastapi:8001"
  DJANGO_BASE: "http://django:8000"
  DJANGO_DEBUG: "False"

---
apiVersion: v1
kind: Secret
metadata:
  name: icmp2-secret
  namespace: icmp2
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DJANGO_SECRET_KEY: "change-me-in-production"
  DISCORD_WEBHOOK_URL: ""
  SLACK_WEBHOOK_URL: ""
  ALERTMANAGER_DISCORD_WEBHOOK_URL: ""
