# Generated by Django 6.0.4 on 2026-04-22 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_name', models.CharField(max_length=200)),
                ('role_code', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dashboard_layouts',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_name', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('chart', '차트'), ('table', '테이블'), ('gauge', '게이지'), ('map', '지도'), ('counter', '카운터')], max_length=20)),
                ('target_type', models.CharField(max_length=50)),
                ('query_config', models.JSONField()),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'dashboard_widgets',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidgetBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widget_bindings', to='dashboard.dashboardlayout')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_bindings', to='dashboard.dashboardwidget')),
            ],
            options={
                'db_table': 'dashboard_widget_bindings',
                'ordering': ['display_order'],
                'unique_together': {('layout', 'widget')},
            },
        ),
    ]
