# Generated by Django 6.0.4 on 2026-05-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_department_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='계정 잠금 여부'),
        ),
    ]
