# Generated by Django 6.0.4 on 2026-05-22 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_is_locked_to_user'),
        ('accounts', '0004_department_created_at_department_updated_at_and_more'),
    ]

    operations = [
    ]
