# Generated by Django 6.0.3 on 2026-04-20 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('threshold', '임계치 초과'), ('missing', '데이터 누락'), ('status', '장비 상태')], max_length=20)),
                ('metric_code', models.CharField(max_length=50)),
                ('condition_operator', models.CharField(max_length=10)),
                ('warning_value', models.FloatField(blank=True, null=True)),
                ('danger_value', models.FloatField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('notify', '알림'), ('shutdown', '장비 차단')], default='notify', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'alarm_rules',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('channel_type', models.CharField(choices=[('email', '이메일'), ('sms', '문자'), ('push', '푸시 알림')], max_length=20)),
                ('title_template', models.CharField(max_length=300)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음'), ('critical', '위험')], max_length=20)),
                ('event_type', models.CharField(choices=[('gas', '유해가스'), ('power', '전력'), ('location', '위치'), ('device', '장비 상태')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('event_status', models.CharField(choices=[('open', '발생'), ('acknowledged', '확인'), ('closed', '종료')], default='open', max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_events', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='monitoring.devicechannel')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='monitoring.device')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_events', to='facilities.facility')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='facilities.worker')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alarmrule')),
            ],
            options={
                'db_table': 'alarm_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('action_note', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_histories', to=settings.AUTH_USER_MODEL)),
                ('alarm_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='alerts.alarmevent')),
            ],
            options={
                'verbose_name_plural': 'event histories',
                'db_table': 'event_histories',
                'ordering': ['-action_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('send_status', models.CharField(choices=[('pending', '대기'), ('sent', '발송 완료'), ('failed', '발송 실패')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alarmevent')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
