# Generated by Django 6.0.4 on 2026-05-11 01:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('monitoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=200)),
                ('channel_type', models.CharField(choices=[('email', '이메일'), ('sms', '문자'), ('push', '푸시 알림')], max_length=20)),
                ('title_template', models.CharField(max_length=300)),
                ('body_template', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='AlarmRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200)),
                ('rule_type', models.CharField(choices=[('threshold', '임계치 초과'), ('missing', '데이터 누락'), ('offline', '장비 오프라인'), ('power', '전력 이상')], max_length=20)),
                ('action_type', models.CharField(choices=[('notify', '알림'), ('shutdown', '장비 차단')], default='notify', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('missing_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('threshold_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_rules', to='monitoring.thresholdpolicy')),
            ],
            options={
                'db_table': 'alarm_rules',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('normal', '정상'), ('warning', '주의'), ('danger', '위험')], db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('gas', '유해가스'), ('power', '전력'), ('location', '위치'), ('device', '장비 상태')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('event_status', models.CharField(choices=[('open', '조치 필요'), ('acknowledged', '조치 중'), ('closed', '조치 완료')], db_index=True, default='open', max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_events', to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='monitoring.devicechannel')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='monitoring.device')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_events', to='facilities.facility')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alarm_events', to='facilities.worker')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alarmrule')),
            ],
            options={
                'db_table': 'alarm_events',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('acknowledge', '확인'), ('close', '종료'), ('reopen', '재오픈')], max_length=20)),
                ('action_note', models.TextField(blank=True)),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_histories', to=settings.AUTH_USER_MODEL)),
                ('alarm_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='alerts.alarmevent')),
            ],
            options={
                'verbose_name_plural': 'event histories',
                'db_table': 'event_histories',
                'ordering': ['-action_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('send_status', models.CharField(choices=[('pending', '대기'), ('sent', '발송 완료'), ('failed', '발송 실패')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alarmevent')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
