# Generated by Django 6.0.4 on 2026-05-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    # updated_by 컬럼은 0002_riskcriteria_alarmrule_updated_by에서 이미 추가됨
    operations = []
