# Generated by Django 6.0.4 on 2026-04-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmevent',
            name='event_status',
            field=models.CharField(choices=[('open', '조치 필요'), ('acknowledged', '조치 중'), ('closed', '조치 완료')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='alarmevent',
            name='severity',
            field=models.CharField(choices=[('normal', '정상'), ('warning', '주의'), ('danger', '위험')], max_length=20),
        ),
    ]
