# Generated by Django 6.0.4 on 2026-05-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_riskcriteria_alarmrule_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmevent',
            name='severity',
            field=models.CharField(choices=[('normal', '정상'), ('warning', '주의'), ('danger', '위험'), ('anomaly', '통계/AI 이상 탐지'), ('predictive_warning', 'AI 조기 예측 경보')], db_index=True, max_length=20),
        ),
    ]
