# Generated by Django 6.0.4 on 2026-05-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_add_anomaly_predictive_warning_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmevent',
            name='current_value',
            field=models.FloatField(blank=True, help_text='마지막 감지 시 측정값 (대표값)', null=True),
        ),
        migrations.AddField(
            model_name='alarmevent',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, help_text='마지막 감지 시각 (이상 지속 시 갱신)', null=True),
        ),
    ]
