# Generated by Django 6.0.4 on 2026-04-23 06:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_backfill_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmevent',
            name='event_status',
            field=models.CharField(choices=[('open', '조치 필요'), ('acknowledged', '조치 중'), ('closed', '조치 완료')], db_index=True, default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='alarmevent',
            name='occurred_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='alarmevent',
            name='severity',
            field=models.CharField(choices=[('normal', '정상'), ('warning', '주의'), ('danger', '위험')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventhistory',
            name='action_type',
            field=models.CharField(choices=[('acknowledge', '확인'), ('close', '종료'), ('reopen', '재오픈')], max_length=20),
        ),
    ]
