# Generated by Django 6.0.4 on 2026-05-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_riskcriteria_alarmrule_updated_by'),
        ('alerts', '0003_add_risk_criteria'),
    ]

    operations = [
    ]
