# Generated by Django 6.0.4 on 2026-04-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_index_alarmevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmrule',
            name='metric_code',
        ),
    ]
