# Generated by Django 6.0.4 on 2026-05-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_add_last_seen_at_current_value_to_alarm_event'),
        ('alerts', '0004_merge_20260513_1315'),
    ]

    operations = [
    ]
