# Generated by Django 6.0.4 on 2026-05-22 07:27

from django.db import migrations, models


def create_ai_rule(apps, schema_editor):
    """STEP F(Isolation Forest) 전용 AlarmRule 시드.

    이 rule 인스턴스로 생성된 이벤트는 STEP B/D/E(THRESHOLD rule)의
    dedup 질의와 rule 단위로 완전히 분리된다.
    """
    AlarmRule = apps.get_model('alerts', 'AlarmRule')
    AlarmRule.objects.get_or_create(
        rule_type='ai',
        defaults={
            'rule_name': 'AI 이상 탐지 (Isolation Forest)',
            'is_active': True,
        },
    )


def remove_ai_rule(apps, schema_editor):
    AlarmRule = apps.get_model('alerts', 'AlarmRule')
    AlarmRule.objects.filter(rule_type='ai').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_merge_20260519_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmrule',
            name='rule_type',
            field=models.CharField(choices=[('threshold', '임계치 초과'), ('missing', '데이터 누락'), ('offline', '장비 오프라인'), ('power', '전력 이상'), ('ai', 'AI 이상 탐지')], max_length=20),
        ),
        migrations.RunPython(create_ai_rule, remove_ai_rule),
    ]
