# Generated by Django 6.0.4 on 2026-05-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0007_alter_alarmrule_rule_type'),
        ('monitoring', '0008_merge_20260519_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(help_text='가스 채널 (co, h2s, ...)', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='갱신 시각 (예측 신선도 감시용)')),
                ('headline_severity', models.CharField(blank=True, help_text='danger / caution / None', max_length=10, null=True)),
                ('headline_confidence', models.CharField(help_text='NORMAL/TENTATIVE/CONFIRMED_WARNING/CONFIRMED_STRONG/UNKNOWN', max_length=20)),
                ('caution_confidence', models.CharField(max_length=20)),
                ('danger_confidence', models.CharField(max_length=20)),
                ('caution_eta_step', models.IntegerField(blank=True, help_text='주의 임계 도달 예측 스텝', null=True)),
                ('danger_eta_step', models.IntegerField(blank=True, null=True)),
                ('path', models.CharField(help_text='normal / degraded / unknown', max_length=10)),
                ('forecast_steps', models.IntegerField(default=0, help_text='예측 수평 H')),
                ('reason', models.TextField(blank=True)),
                ('forecast_mean', models.JSONField(blank=True, null=True)),
                ('ci_lower', models.JSONField(blank=True, null=True)),
                ('ci_upper', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_snapshots', to='monitoring.device')),
            ],
            options={
                'db_table': 'forecast_snapshots',
                'ordering': ['device', 'sensor_type'],
                'unique_together': {('device', 'sensor_type')},
            },
        ),
    ]
