# Generated by Django 6.0.4 on 2026-05-23 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_forecastsnapshot'),
        ('monitoring', '0009_alter_powerreading_current_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastsnapshot',
            options={'ordering': ['device', 'channel', 'sensor_type']},
        ),
        migrations.AlterUniqueTogether(
            name='forecastsnapshot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='forecastsnapshot',
            name='channel',
            field=models.ForeignKey(blank=True, help_text='전력 채널 (gas는 NULL)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_snapshots', to='monitoring.devicechannel'),
        ),
        migrations.AlterField(
            model_name='forecastsnapshot',
            name='sensor_type',
            field=models.CharField(help_text='채널 종류 (gas: co/h2s/..., power: voltage/current/power)', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='forecastsnapshot',
            unique_together={('device', 'channel', 'sensor_type')},
        ),
    ]
