# Generated by Django 6.0.4 on 2026-05-27 07:16

from django.db import migrations, models


def offline_to_missing(apps, schema_editor):
    AlarmRule = apps.get_model('alerts', 'AlarmRule')
    AlarmRule.objects.filter(rule_type='offline').update(rule_type='missing')


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_alter_forecastsnapshot_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmrule',
            name='rule_type',
            field=models.CharField(choices=[('threshold', '임계치 초과'), ('missing', '데이터 누락'), ('power', '전력 이상'), ('ai', 'AI 이상 탐지'), ('forecast', 'AI 예측 경보')], max_length=20),
        ),
        migrations.RunPython(offline_to_missing, migrations.RunPython.noop),
    ]
