# Generated by Django 6.0.4 on 2026-05-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_remove_offline_ruletype_merge_into_missing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskcriteria',
            name='color_type',
            field=models.CharField(choices=[('green', '녹색'), ('yellow', '황색'), ('orange', '주황'), ('red', '적색'), ('purple', '보라'), ('gray', '회색')], default='gray', max_length=20),
        ),
    ]
