# Generated by Django 6.0.4 on 2026-06-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0011_alter_riskcriteria_color_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('STARTED', '처리 중'), ('SUCCESS', '성공'), ('FAILURE', '실패'), ('RETRY', '재시도')], default='PENDING', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='PENDING 기록 시각')),
                ('started_at', models.DateTimeField(blank=True, help_text='worker 실행 시작 시각', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='완료(성공/실패) 시각', null=True)),
            ],
            options={
                'verbose_name': '태스크 로그',
                'verbose_name_plural': '태스크 로그 목록',
                'db_table': 'task_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
