# Generated by Django 6.0.4 on 2026-04-22 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=50, unique=True)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
                ('warning_min', models.FloatField(blank=True, null=True)),
                ('warning_max', models.FloatField(blank=True, null=True)),
                ('danger_min', models.FloatField(blank=True, null=True)),
                ('danger_max', models.FloatField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('alert', '알림'), ('shutdown', '장비 차단')], default='alert', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'threshold_policies',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('gas', '유해가스 센서'), ('power', '스마트 전력계')], max_length=20)),
                ('device_uid', models.CharField(max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('software_version', models.CharField(blank=True, max_length=50)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '정상'), ('inactive', '비활성'), ('fault', '장애')], default='active', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.building')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='facilities.facility')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.floor')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.zone')),
            ],
            options={
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_no', models.PositiveIntegerField()),
                ('channel_code', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성')], default='active', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='monitoring.device')),
            ],
            options={
                'db_table': 'device_channels',
                'unique_together': {('device', 'channel_no')},
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=50)),
                ('status_message', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='monitoring.device')),
            ],
            options={
                'db_table': 'device_status_logs',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.FloatField(blank=True, null=True)),
                ('h2s', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('o2', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('nh3', models.FloatField(blank=True, null=True)),
                ('voc', models.FloatField(blank=True, null=True)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_readings', to='monitoring.device')),
            ],
            options={
                'db_table': 'gas_readings',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(blank=True, null=True)),
                ('voltage_value', models.FloatField(blank=True, null=True)),
                ('power_value', models.FloatField(blank=True, null=True)),
                ('power_status', models.CharField(blank=True, max_length=50)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_readings', to='monitoring.devicechannel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_readings', to='monitoring.device')),
            ],
            options={
                'db_table': 'power_readings',
                'ordering': ['-measured_at'],
            },
        ),
    ]
