# Generated by Django 6.0.4 on 2026-04-21 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=50, unique=True)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
                ('warning_min', models.FloatField(blank=True, null=True)),
                ('warning_max', models.FloatField(blank=True, null=True)),
                ('danger_min', models.FloatField(blank=True, null=True)),
                ('danger_max', models.FloatField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('alert', '알림'), ('shutdown', '장비 차단')], default='alert', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '임계치 정책',
                'verbose_name_plural': '임계치 정책 목록',
                'db_table': 'threshold_policies',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('gas', '유해가스 센서'), ('power', '스마트 파워 디바이스')], max_length=20)),
                ('device_code', models.CharField(help_text='장비 코드 ex) 001', max_length=50)),
                ('device_uid', models.CharField(help_text='MAC address', max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('software_version', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='장비 통신 IP', null=True)),
                ('port', models.PositiveIntegerField(help_text='통신 PORT')),
                ('is_active', models.BooleanField(default=True, help_text='사용 여부')),
                ('installed_at', models.DateTimeField(blank=True, help_text='설치일', null=True)),
                ('status', models.CharField(choices=[('active', '정상'), ('inactive', '비활성'), ('fault', '장애')], default='active', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='마지막 연결일시', null=True)),
                ('note', models.TextField(blank=True, help_text='비고')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.building')),
                ('connected_facility', models.ForeignKey(blank=True, help_text='연결 설비', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connected_devices', to='facilities.facility')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='accounts.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='facilities.facility')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.floor')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_devices', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.zone')),
            ],
            options={
                'verbose_name': '장비',
                'verbose_name_plural': '장비 목록',
                'db_table': 'devices',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_no', models.PositiveIntegerField()),
                ('channel_code', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성')], default='active', max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='monitoring.device')),
            ],
            options={
                'db_table': 'device_channels',
                'unique_together': {('device', 'channel_no')},
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=50)),
                ('status_message', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='monitoring.device')),
            ],
            options={
                'verbose_name': '장비 상태 이력',
                'verbose_name_plural': '장비 상태 이력 목록',
                'db_table': 'device_status_logs',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.FloatField(blank=True, help_text='일산화탄소 ppm', null=True)),
                ('h2s', models.FloatField(blank=True, help_text='황화수소 ppm', null=True)),
                ('co2', models.FloatField(blank=True, help_text='이산화탄소 ppm', null=True)),
                ('o2', models.FloatField(blank=True, help_text='산소 %', null=True)),
                ('no2', models.FloatField(blank=True, help_text='이산화질소 ppm', null=True)),
                ('so2', models.FloatField(blank=True, help_text='이산화황 ppm', null=True)),
                ('o3', models.FloatField(blank=True, help_text='오존 ppm', null=True)),
                ('nh3', models.FloatField(blank=True, help_text='암모니아 ppm', null=True)),
                ('voc', models.FloatField(blank=True, help_text='휘발성유기화합물 ppm', null=True)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gas_readings', to='monitoring.device')),
            ],
            options={
                'verbose_name': '유해가스 측정값',
                'verbose_name_plural': '유해가스 측정값 목록',
                'db_table': 'gas_readings',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('regular', '정기 점검'), ('abnormal', '이상 점검')], max_length=20)),
                ('inspection_date', models.DateField(help_text='점검일')),
                ('status', models.CharField(choices=[('normal', '정상'), ('action_required', '조치 필요')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='점검 의견')),
                ('expected_action_date', models.DateField(blank=True, help_text='예상 조치일', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='monitoring.device')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '점검 이력',
                'verbose_name_plural': '점검 이력 목록',
                'db_table': 'inspection_logs',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(help_text='조치 완료일')),
                ('action_note', models.TextField(blank=True, help_text='조치 의견')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action', to='monitoring.inspectionlog')),
            ],
            options={
                'verbose_name': '조치 이력',
                'verbose_name_plural': '조치 이력 목록',
                'db_table': 'action_logs',
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.FloatField(default=-1, help_text='전류 A, 통신불능=-1')),
                ('voltage_value', models.FloatField(default=-1, help_text='전압 V, 통신불능=-1')),
                ('power_value', models.FloatField(default=-1, help_text='전력 W, 통신불능=-1')),
                ('power_status', models.CharField(blank=True, choices=[('on', 'ON'), ('off', 'OFF'), ('error', '통신불능')], max_length=10, null=True)),
                ('measured_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_readings', to='monitoring.devicechannel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_readings', to='monitoring.device')),
            ],
            options={
                'verbose_name': '전력 측정값',
                'verbose_name_plural': '전력 측정값 목록',
                'db_table': 'power_readings',
                'ordering': ['-measured_at'],
            },
        ),
    ]
