# Generated by Django 6.0.4 on 2026-05-11 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThresholdPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_code', models.CharField(max_length=50, unique=True)),
                ('normal_min', models.FloatField(blank=True, null=True)),
                ('normal_max', models.FloatField(blank=True, null=True)),
                ('warning_min', models.FloatField(blank=True, null=True)),
                ('warning_max', models.FloatField(blank=True, null=True)),
                ('danger_min', models.FloatField(blank=True, null=True)),
                ('danger_max', models.FloatField(blank=True, null=True)),
                ('action_type', models.CharField(choices=[('alert', '알림'), ('shutdown', '장비 차단')], default='alert', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '임계치 정책',
                'verbose_name_plural': '임계치 정책 목록',
                'db_table': 'threshold_policies',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('gas', '유해가스 센서'), ('power', '스마트 파워 디바이스')], max_length=20)),
                ('device_code', models.CharField(help_text='장비 코드 ex) 001', max_length=50)),
                ('device_uid', models.CharField(help_text='MAC address', max_length=100, unique=True)),
                ('device_name', models.CharField(max_length=200)),
                ('software_version', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(help_text='장비 통신 IP', null=True)),
                ('port', models.PositiveIntegerField(help_text='통신 PORT')),
                ('is_active', models.BooleanField(default=True, help_text='사용 여부')),
                ('installed_at', models.DateTimeField(blank=True, help_text='설치일', null=True)),
                ('status', models.CharField(choices=[('active', '정상'), ('inactive', '비활성'), ('fault', '장애')], default='active', max_length=20)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='마지막 연결일시', null=True)),
                ('note', models.TextField(blank=True, help_text='비고')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.building')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='accounts.department')),
                ('equipment', models.ForeignKey(blank=True, help_text='연결 설비', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.equipment')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='facilities.facility')),
                ('floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.floor')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_devices', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.zone')),
            ],
            options={
                'verbose_name': '장비',
                'verbose_name_plural': '장비 목록',
                'db_table': 'devices',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_code', models.CharField(choices=[('slave01', '1CH'), ('slave02', '2CH'), ('slave11', '3CH'), ('slave12', '4CH'), ('slave21', '5CH'), ('slave22', '6CH'), ('slave31', '7CH'), ('slave32', '8CH'), ('slave41', '9CH'), ('slave42', '10CH'), ('slave51', '11CH'), ('slave52', '12CH'), ('slave61', '13CH'), ('slave62', '14CH'), ('slave71', '15CH'), ('slave72', '16CH')], help_text='slave01~slave72', max_length=10)),
                ('channel_name', models.CharField(blank=True, help_text='관리자 등록 채널명 ex) 압연기 전원', max_length=100)),
                ('x_position', models.FloatField(blank=True, help_text='공장 지도 X좌표', null=True)),
                ('y_position', models.FloatField(blank=True, help_text='공장 지도 Y좌표', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='ON/OFF 스위치 상태')),
                ('status', models.CharField(choices=[('active', '활성'), ('inactive', '비활성')], default='active', max_length=20)),
                ('rated_power_w', models.PositiveIntegerField(default=1000, help_text='채널 정격 전력(W). 카탈로그 기준 1CH Max 1000W. 설비별 실제값으로 수정 하도록')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='monitoring.device')),
            ],
            options={
                'verbose_name': '장비 채널',
                'verbose_name_plural': '장비 채널 목록',
                'db_table': 'device_channels',
                'unique_together': {('device', 'channel_code')},
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=50)),
                ('status_message', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='monitoring.device')),
            ],
            options={
                'verbose_name': '장비 상태 이력',
                'verbose_name_plural': '장비 상태 이력 목록',
                'db_table': 'device_status_logs',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('regular', '정기 점검'), ('abnormal', '이상 점검')], max_length=20)),
                ('inspection_date', models.DateField(help_text='점검일')),
                ('status', models.CharField(choices=[('normal', '정상'), ('action_required', '조치 필요')], max_length=20)),
                ('note', models.TextField(blank=True, help_text='점검 의견')),
                ('expected_action_date', models.DateField(blank=True, help_text='예상 조치일', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='monitoring.device')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '점검 이력',
                'verbose_name_plural': '점검 이력 목록',
                'db_table': 'inspection_logs',
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_date', models.DateField(help_text='조치 완료일')),
                ('action_note', models.TextField(blank=True, help_text='조치 의견')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('inspection', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='action', to='monitoring.inspectionlog')),
            ],
            options={
                'verbose_name': '조치 이력',
                'verbose_name_plural': '조치 이력 목록',
                'db_table': 'action_logs',
            },
        ),
        migrations.CreateModel(
            name='PowerStatusReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_value', models.IntegerField(help_text='ON=255 / OFF=0')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_readings', to='monitoring.devicechannel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_status_readings', to='monitoring.device')),
            ],
            options={
                'verbose_name': '전력 ON/OFF 상태',
                'verbose_name_plural': '전력 ON/OFF 상태 목록',
                'db_table': 'power_status_readings',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='GasReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.FloatField(blank=True, help_text='일산화탄소 ppm', null=True)),
                ('h2s', models.FloatField(blank=True, help_text='황화수소 ppm', null=True)),
                ('co2', models.FloatField(blank=True, help_text='이산화탄소 ppm', null=True)),
                ('o2', models.FloatField(blank=True, help_text='산소 %', null=True)),
                ('no2', models.FloatField(blank=True, help_text='이산화질소 ppm', null=True)),
                ('so2', models.FloatField(blank=True, help_text='이산화황 ppm', null=True)),
                ('o3', models.FloatField(blank=True, help_text='오존 ppm', null=True)),
                ('nh3', models.FloatField(blank=True, help_text='암모니아 ppm', null=True)),
                ('voc', models.FloatField(blank=True, help_text='휘발성유기화합물 ppm', null=True)),
                ('measured_at', models.DateTimeField(db_index=True, help_text='센서 측정 시각')),
                ('received_at', models.DateTimeField(auto_now_add=True, help_text='서버 수신 시각')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gas_readings', to='monitoring.device')),
            ],
            options={
                'verbose_name': '유해가스 측정값',
                'verbose_name_plural': '유해가스 측정값 목록',
                'db_table': 'gas_readings',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['device', 'measured_at'], name='gas_reading_device__76764d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PowerReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_a', models.IntegerField(default=-1, help_text='전류 A, -1=통신불능')),
                ('voltage_v', models.IntegerField(default=-1, help_text='전압 V, -1=통신불능')),
                ('power_w', models.IntegerField(default=-1, help_text='전력 W, -1=통신불능')),
                ('measured_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_readings', to='monitoring.devicechannel')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_readings', to='monitoring.device')),
            ],
            options={
                'verbose_name': '스마트파워 측정값',
                'verbose_name_plural': '스마트파워 측정값 목록',
                'db_table': 'power_readings',
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['channel', 'measured_at'], name='power_readi_channel_a5e44e_idx')],
            },
        ),
    ]
