# Generated by Django 6.0.4 on 2026-04-24 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_equipment'),
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerStatusReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_value', models.IntegerField(help_text='ON=255 / OFF=0')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '전력 ON/OFF 상태',
                'verbose_name_plural': '전력 ON/OFF 상태 목록',
                'db_table': 'power_status_readings',
                'ordering': ['-received_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='devicechannel',
            options={'verbose_name': '장비 채널', 'verbose_name_plural': '장비 채널 목록'},
        ),
        migrations.AlterModelOptions(
            name='powerreading',
            options={'ordering': ['-measured_at'], 'verbose_name': '스마트파워 측정값', 'verbose_name_plural': '스마트파워 측정값 목록'},
        ),
        migrations.RemoveField(
            model_name='device',
            name='connected_facility',
        ),
        migrations.AlterUniqueTogether(
            name='devicechannel',
            unique_together={('device', 'channel_code')},
        ),
        migrations.RemoveField(
            model_name='powerreading',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='powerreading',
            name='power_status',
        ),
        migrations.RemoveField(
            model_name='powerreading',
            name='power_value',
        ),
        migrations.RemoveField(
            model_name='powerreading',
            name='voltage_value',
        ),
        migrations.AddField(
            model_name='device',
            name='equipment',
            field=models.ForeignKey(blank=True, help_text='연결 설비', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='facilities.equipment'),
        ),
        migrations.AddField(
            model_name='devicechannel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='ON/OFF 스위치 상태'),
        ),
        migrations.AddField(
            model_name='devicechannel',
            name='x_position',
            field=models.FloatField(blank=True, help_text='공장 지도 X좌표', null=True),
        ),
        migrations.AddField(
            model_name='devicechannel',
            name='y_position',
            field=models.FloatField(blank=True, help_text='공장 지도 Y좌표', null=True),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='current_a',
            field=models.IntegerField(default=-1, help_text='전류 A, -1=통신불능'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='power_w',
            field=models.IntegerField(default=-1, help_text='전력 W, -1=통신불능'),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='voltage_v',
            field=models.IntegerField(default=-1, help_text='전압 V, -1=통신불능'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='inspection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='action', to='monitoring.inspectionlog'),
        ),
        migrations.AlterField(
            model_name='device',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='devicechannel',
            name='channel_code',
            field=models.CharField(choices=[('slave01', '1CH'), ('slave02', '2CH'), ('slave11', '3CH'), ('slave12', '4CH'), ('slave21', '5CH'), ('slave22', '6CH'), ('slave31', '7CH'), ('slave32', '8CH'), ('slave41', '9CH'), ('slave42', '10CH'), ('slave51', '11CH'), ('slave52', '12CH'), ('slave61', '13CH'), ('slave62', '14CH'), ('slave71', '15CH'), ('slave72', '16CH')], help_text='slave01~slave72', max_length=10),
        ),
        migrations.AlterField(
            model_name='devicechannel',
            name='channel_name',
            field=models.CharField(blank=True, help_text='관리자 등록 채널명 ex) 압연기 전원', max_length=100),
        ),
        migrations.AlterField(
            model_name='devicestatuslog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_logs', to='monitoring.device'),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gas_readings', to='monitoring.device'),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='measured_at',
            field=models.DateTimeField(db_index=True, help_text='센서 측정 시각'),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, help_text='서버 수신 시각'),
        ),
        migrations.AlterField(
            model_name='inspectionlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='monitoring.device'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_readings', to='monitoring.devicechannel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_readings', to='monitoring.device'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='measured_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='gasreading',
            index=models.Index(fields=['device', 'measured_at'], name='gas_reading_device__76764d_idx'),
        ),
        migrations.AddIndex(
            model_name='powerreading',
            index=models.Index(fields=['channel', 'measured_at'], name='power_readi_channel_a5e44e_idx'),
        ),
        migrations.AddField(
            model_name='powerstatusreading',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_readings', to='monitoring.devicechannel'),
        ),
        migrations.AddField(
            model_name='powerstatusreading',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='power_status_readings', to='monitoring.device'),
        ),
        migrations.RemoveField(
            model_name='devicechannel',
            name='channel_no',
        ),
        migrations.RemoveField(
            model_name='devicechannel',
            name='channel_type',
        ),
    ]
