# Generated by Django 6.0.4 on 2026-05-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_type',
            field=models.CharField(choices=[('gas', '유해가스 센서'), ('power', '스마트 파워 디바이스'), ('loc', '위치 노드')], max_length=20),
        ),
    ]
