# Generated by Django 6.0.4 on 2026-05-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thresholdpolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='thresholdpolicy',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
