# Generated by Django 6.0.4 on 2026-05-13 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0009_add_equipment_admin_fields'),
        ('monitoring', '0002_add_loc_device_type'),
    ]

    # 모든 operations이 0002_add_threshold_audit_fields, 0003_thresholdpolicy_new_fields,
    # 0004_thresholdpolicy_unique_metric_category, 0005_add_temperature_to_power_reading,
    # 0006_add_node_reading에서 이미 처리됨
    operations = []
