# Generated by Django 6.0.4 on 2026-04-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_powerstatusreading_alter_devicechannel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicechannel',
            name='rated_power_w',
            field=models.PositiveIntegerField(default=1000, help_text='채널 정격 전력(W). 카탈로그 기준 1CH Max 1000W. 설비별 실제값으로 수정 하도록'),
        ),
    ]
