# Generated by Django 6.0.4 on 2026-05-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_powerreading_temperature_c_thresholdpolicy_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasreading',
            name='quality_flag',
            field=models.CharField(default='ok', help_text='ok / missing / comm_err / partial', max_length=20),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='raw_payload',
            field=models.JSONField(blank=True, help_text='원본 수신 payload', null=True),
        ),
    ]
