# Generated by Django 6.0.4 on 2026-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_thresholdpolicy_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdpolicy',
            name='metric_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='thresholdpolicy',
            unique_together={('metric_code', 'category')},
        ),
    ]
