# Generated by Django 6.0.4 on 2026-05-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_add_quality_flag_raw_payload_to_gas_reading'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gasreading',
            unique_together={('device', 'measured_at')},
        ),
    ]
