# Generated by Django 6.0.4 on 2026-05-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_thresholdpolicy_unique_metric_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerreading',
            name='temperature_c',
            field=models.FloatField(blank=True, help_text='온도 ℃', null=True),
        ),
    ]
