# Generated by Django 6.0.4 on 2026-05-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_add_unique_device_measured_at_to_gas_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerreading',
            name='quality_flag',
            field=models.CharField(default='ok', help_text='ok / missing / comm_err / partial', max_length=20),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='raw_payload',
            field=models.JSONField(blank=True, help_text='원본 수신 payload', null=True),
        ),
    ]
