# Generated by Django 6.0.4 on 2026-05-12 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('monitoring', '0005_add_temperature_to_power_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(blank=True, help_text='수신 X 좌표', null=True)),
                ('y', models.FloatField(blank=True, help_text='수신 Y 좌표', null=True)),
                ('received_at', models.DateTimeField(db_index=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='facilities.locationnode')),
            ],
            options={
                'verbose_name': '위치 노드 수신 로그',
                'verbose_name_plural': '위치 노드 수신 로그 목록',
                'db_table': 'node_readings',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['node', 'received_at'], name='node_readin_node_id_efadc3_idx')],
            },
        ),
    ]
