# Generated by Django 6.0.4 on 2026-05-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_powerreading_temperature_c_thresholdpolicy_category_and_more'),
        ('monitoring', '0006_add_node_reading'),
    ]

    operations = [
    ]
