# Generated by Django 6.0.4 on 2026-05-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_add_quality_flag_raw_payload_to_power_reading'),
        ('monitoring', '0007_merge_20260513_1315'),
    ]

    operations = [
    ]
