# Generated by Django 6.0.4 on 2026-05-23 07:43
# Phase C-5-3 — IntegerField → FloatField + raw_payload에서 float 원본 복원.

from django.db import migrations, models


def restore_from_raw_payload(apps, schema_editor):
    """Phase C-5-3 — raw_payload(jsonb)에서 float 원본 값을 컬럼에 복원.

    배경: IntegerField 시절 송수신 float 0.1 정밀도가 컬럼 저장 시 truncation.
    raw_payload에는 원본 float 보존 (1,622건 100% 보존 확인).
    분석 시점: 손실 발생 — current_a 72.9%, power_w 77.2% (평균 0.291A, 0.372W).

    AlterField 직후 RunPython으로 PostgreSQL raw SQL UPDATE 실행.
    1,622건 < 1초 예상.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            UPDATE power_readings
            SET current_a = (raw_payload->>'current_a')::float,
                voltage_v = (raw_payload->>'voltage_v')::float,
                power_w   = (raw_payload->>'power_w')::float
            WHERE raw_payload IS NOT NULL
              AND raw_payload ? 'current_a'
              AND raw_payload ? 'voltage_v'
              AND raw_payload ? 'power_w'
              AND raw_payload->>'current_a' IS NOT NULL
              AND raw_payload->>'voltage_v' IS NOT NULL
              AND raw_payload->>'power_w' IS NOT NULL
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_merge_20260519_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerreading',
            name='current_a',
            field=models.FloatField(default=-1.0, help_text='전류 A, -1=통신불능'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='power_w',
            field=models.FloatField(default=-1.0, help_text='전력 W, -1=통신불능'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='voltage_v',
            field=models.FloatField(default=-1.0, help_text='전압 V, -1=통신불능'),
        ),
        migrations.RunPython(
            restore_from_raw_payload,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
