# Generated by Django 6.0.4 on 2026-05-27 06:44

from django.db import migrations, models


def alert_to_notify(apps, schema_editor):
    ThresholdPolicy = apps.get_model('monitoring', 'ThresholdPolicy')
    ThresholdPolicy.objects.filter(action_type='alert').update(action_type='notify')


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_alter_powerreading_current_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thresholdpolicy',
            name='action_type',
            field=models.CharField(choices=[('notify', '알림'), ('shutdown', '장비 차단')], default='notify', max_length=20),
        ),
        migrations.RunPython(alert_to_notify, migrations.RunPython.noop),
    ]
