# Generated by Django 6.0.4 on 2026-06-01 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_alter_thresholdpolicy_action_type_alert_to_notify'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('device_uid', models.CharField(db_index=True, max_length=100)),
                ('reason', models.CharField(help_text='device_not_found / inactive / invalid_range / parse_fail 등', max_length=100)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'drop_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='gasreading',
            name='event_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='측정 1건 고유 ID — 원천↔파생 DetectionResult↔알람 상관 키', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='tick_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='한 emit 사이클 공유 ID — 가스·전력·위치 교차 상관', null=True),
        ),
        migrations.AddField(
            model_name='gasreading',
            name='ts_fallback',
            field=models.BooleanField(default=False, help_text='measured_at 파싱 실패로 서버 now() 대체됐는지'),
        ),
        migrations.AlterField(
            model_name='gasreading',
            name='quality_flag',
            field=models.CharField(default='ok', help_text='ok / missing / comm_err / partial / invalid', max_length=20),
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, help_text='원천 GasReading.event_id 계보 키')),
                ('sensor_type', models.CharField(blank=True, help_text='채널/가스종. IF는 null=9채널 전체', max_length=20, null=True)),
                ('stage', models.CharField(choices=[('THRESHOLD', '임계 판정'), ('ZSCORE', 'Z-score'), ('CHANGEPOINT', '변화점'), ('IF', 'Isolation Forest'), ('ARIMA', 'ARIMA 예측')], db_index=True, max_length=20)),
                ('level', models.CharField(help_text='판정 등급 (정상/주의/위험/이상 등)', max_length=20)),
                ('score', models.FloatField(blank=True, help_text='수치 (z·mahalanobis·예측편차 등)', null=True)),
                ('detail', models.JSONField(blank=True, help_text='단계별 상세 (anchor·곡선·임계비교 등)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detections', to='monitoring.device')),
                ('gas_reading', models.ForeignKey(blank=True, help_text='원천 참조 (event_id로도 연결되나 FK 편의)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='monitoring.gasreading')),
            ],
            options={
                'db_table': 'detection_results',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='detection_r_event_i_d77fd8_idx'), models.Index(fields=['device', 'sensor_type', 'created_at'], name='detection_r_device__c8cbc9_idx'), models.Index(fields=['stage', 'level'], name='detection_r_stage_7bffce_idx')],
            },
        ),
    ]
