# Generated by Django 6.0.4 on 2026-06-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_droplog_gasreading_event_id_gasreading_tick_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powerreading',
            name='event_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='측정 1건 고유 ID — 원천↔DetectionResult↔알람 상관 키', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='tick_id',
            field=models.UUIDField(blank=True, db_index=True, help_text='한 emit 사이클 공유 ID (교차 상관, 현재 보류)', null=True),
        ),
        migrations.AddField(
            model_name='powerreading',
            name='ts_fallback',
            field=models.BooleanField(default=False, help_text='measured_at 파싱 실패로 서버 now() 대체됐는지'),
        ),
        migrations.AlterField(
            model_name='powerreading',
            name='quality_flag',
            field=models.CharField(default='ok', help_text='ok / missing / comm_err / partial / invalid', max_length=20),
        ),
    ]
