# Generated by Django 6.0.4 on 2026-06-01 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_powerreading_event_id_powerreading_tick_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='stage',
            field=models.CharField(choices=[('THRESHOLD', '임계 판정'), ('ZSCORE', 'Z-score'), ('CHANGEPOINT', '변화점'), ('IF', 'Isolation Forest'), ('ARIMA', 'ARIMA 예측'), ('POLICY', '정책 엔진 (현재 상태 통합)')], db_index=True, max_length=20),
        ),
    ]
