# Generated by Django 6.0.4 on 2026-06-04 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_rename_event_id_to_trace_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='detectionresult',
            name='detection_r_event_i_d77fd8_idx',
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='gas_reading',
            field=models.ForeignKey(blank=True, help_text='원천 참조 (trace_id로도 연결되나 FK 편의)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='monitoring.gasreading'),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='trace_id',
            field=models.UUIDField(db_index=True, help_text='원천 GasReading.trace_id 계보 키'),
        ),
        migrations.AddIndex(
            model_name='detectionresult',
            index=models.Index(fields=['trace_id'], name='detection_r_trace_i_a13bce_idx'),
        ),
    ]
