# Generated by Django 6.0.4 on 2026-05-13 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='정책명')),
                ('event_type', models.CharField(choices=[('가스 경보', '가스 경보'), ('전력 이상', '전력 이상'), ('위험구역 진입', '위험구역 진입'), ('PPE 미착용', 'PPE 미착용'), ('작업 안전 체크리스트 미완료', '작업 안전 체크리스트 미완료'), ('VR 교육 미이수', 'VR 교육 미이수')], max_length=50, verbose_name='이벤트 상세')),
                ('channels', models.CharField(max_length=100, verbose_name='발송 채널')),
                ('targets', models.CharField(max_length=100, verbose_name='수신 대상')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 여부')),
                ('condition_summary', models.TextField(blank=True, verbose_name='적용 조건 요약')),
                ('alarm_title', models.CharField(blank=True, max_length=200, verbose_name='알림 제목')),
                ('alarm_content', models.TextField(blank=True, verbose_name='알림 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '알림 정책',
                'verbose_name_plural': '알림 정책 목록',
                'db_table': 'alarm_policies',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VREducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='교육명')),
                ('target', models.CharField(max_length=100, verbose_name='적용 대상')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용 상태')),
                ('duration', models.PositiveIntegerField(default=0, verbose_name='재생 시간(초)')),
                ('description', models.TextField(blank=True, verbose_name='교육 설명')),
                ('memo', models.TextField(blank=True, verbose_name='운영 메모')),
                ('video', models.FileField(blank=True, null=True, upload_to='vr_education/videos/', verbose_name='영상 파일')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='vr_education/thumbnails/', verbose_name='썸네일')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'VR 교육',
                'db_table': 'vr_educations',
            },
        ),
        migrations.CreateModel(
            name='AlarmSendHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(verbose_name='발송 시각')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('이메일', '이메일'), ('앱 푸시', '앱 푸시'), ('관제 실시간 알림', '관제 실시간 알림')], max_length=20, verbose_name='발송 채널')),
                ('targets', models.CharField(max_length=100, verbose_name='수신 역할')),
                ('result', models.CharField(choices=[('성공', '성공'), ('실패', '실패'), ('지연', '지연')], max_length=10, verbose_name='발송 결과')),
                ('policy_name', models.CharField(blank=True, max_length=200, verbose_name='연결 알림 정책명')),
                ('scope', models.CharField(blank=True, max_length=100, verbose_name='적용 역할 범위')),
                ('content', models.TextField(verbose_name='발송 내용')),
                ('reason', models.TextField(blank=True, verbose_name='결과 메모')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alarm_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='send_histories', to='manager.alarmpolicy', verbose_name='연결 정책')),
            ],
            options={
                'verbose_name': '알림 발송 이력',
                'verbose_name_plural': '알림 발송 이력 목록',
                'db_table': 'alarm_send_histories',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(verbose_name='스냅샷 데이터')),
                ('saved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='저장자')),
            ],
            options={
                'verbose_name': '체크리스트 반영 이력',
                'db_table': 'checklist_snapshots',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('gas', '유해가스 센서'), ('power', '스마트 전력 시스템'), ('node', '위치 노드')], max_length=20)),
                ('data_category', models.CharField(choices=[('raw', '원천 로그'), ('event', '이벤트 이력'), ('aggregate', '집계 이력'), ('location', '위치 이력')], max_length=20)),
                ('origin_days', models.PositiveIntegerField(help_text='원천 데이터 보관 기간(일)')),
                ('history_days', models.PositiveIntegerField(help_text='이력 데이터 보관 기간(일)')),
                ('delete_schedule', models.CharField(choices=[('daily', '매일'), ('monthly_1', '매월 1일'), ('monthly_15', '매월 15일'), ('monthly_last', '매월 말일'), ('quarterly', '분기말')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('memo', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '데이터 보관 주기',
                'verbose_name_plural': '데이터 보관 주기 목록',
                'db_table': 'data_retention_policies',
                'ordering': ['device_type', 'data_category'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='공지 제목')),
                ('category', models.CharField(choices=[('운영 공지', '운영 공지'), ('안전 공지', '안전 공지'), ('시스템 공지', '시스템 공지')], max_length=20, verbose_name='게시 구분')),
                ('content', models.TextField(verbose_name='공지 내용')),
                ('is_exposed', models.BooleanField(default=True, verbose_name='노출 여부')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '공지사항',
                'verbose_name_plural': '공지사항 목록',
                'db_table': 'notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='notices/', verbose_name='파일')),
                ('original_name', models.CharField(max_length=255, verbose_name='원본 파일명')),
                ('file_size', models.PositiveIntegerField(verbose_name='파일 크기(bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='manager.notice')),
            ],
            options={
                'verbose_name': '공지 첨부파일',
                'db_table': 'notice_attachments',
            },
        ),
    ]
